#!/usr/bin/python

# apt-get install python-netifaces

import netifaces
import socket 

print 'Interfaces available: ' 
print netifaces.interfaces()
intface = raw_input("Which interface would you like to probe above?: ")
eth0_addresses = netifaces.ifaddresses(intface)

interface_info = eth0_addresses[socket.AF_INET][0]

print interface_info['addr']
print interface_info['netmask']

 
